const MODELS={"upscayl-standard-4x":{name:"enhance 标准",description:"适用于大多数图像，整体效果均衡。"},"upscayl-lite-4x":{name:"enhance 轻量版",description:"速度较快，质量损失较小。"},"high-fidelity-4x":{name:"高保真",description:"注重还原真实细节，适合照片。"},"remacri-4x":{name:"Remacri",description:"适合自然图像，强调锐度和细节。"},"ultramix-balanced-4x":{name:"Ultramix",description:"在锐度和细节之间取得平衡。"},"ultrasharp-4x":{name:"Ultrasharp",description:"重点增强边缘和纹理锐度。"},"digital-art-4x":{name:"数字艺术",description:"适合数字艺术、插画和动漫。"}};
const $=id=>document.getElementById(id),e={file:$('fileInput'),drop:$('dropzone'),list:$('fileQueue'),count:$('queueCount'),clear:$('clearFile'),model:$('modelSelect'),trigger:$('modelTrigger'),triggerName:$('modelTriggerName'),desc:$('modelDescription'),dialog:$('modelDialog'),grid:$('modelGrid'),scale:$('scaleSelect'),format:$('formatSelect'),tile:$('tileSelect'),start:$('upscaleButton'),error:$('errorMessage'),status:$('resultStatus'),resultSelect:$('resultImageSelect'),loading:$('loadingResult'),title:$('loadingTitle'),copy:$('loadingCopy'),comparison:$('comparison'),comparisonImage:document.querySelector('.comparison-image'),comparisonAfter:$('comparisonAfter'),handle:$('comparisonHandle'),input:$('inputPreview'),output:$('outputPreview'),footer:$('resultFooter'),info:$('outputInfo'),name:$('outputName'),download:$('downloadButton'),batchDownload:$('batchDownloadButton'),progress:$('progressText')};
let queue=[],active=0,submitting=false;
let comparePosition=50,draggingCompare=false;
const API_BASE='http://127.0.0.1:3000',base=()=>API_BASE,bytes=b=>b<1048576?`${Math.max(1,Math.round(b/1024))} KB`:`${(b/1048576).toFixed(1)} MB`;
function error(text){e.error.textContent=text;e.error.hidden=false}function clearError(){e.error.hidden=true;e.error.textContent=''}
function valid(f){if(!/^image\/(png|jpeg|webp)$/.test(f.type))return'只支持 PNG、JPG/JPEG 和 WEBP 图片。';if(f.size>50*1048576)return'图片超过 API 的 50 MB 大小限制。';return''}
function addFiles(files){if(submitting)return;clearError();for(const f of Array.from(files||[])){const err=valid(f);if(err){error(`${f.name}：${err}`);continue}if(queue.length>=10||queue.some(x=>x.file.name===f.name&&x.file.size===f.size))continue;queue.push({file:f,status:'queued',inputUrl:URL.createObjectURL(f),jobId:null})}render();if(queue.length)select(queue.length-1)}
function text(i){return i.status==='queued'?`排队中${i.position?` · 前方 ${i.position-1}`:''}`:i.status==='running'?`处理中${i.progress!=null?` · ${i.progress}%`:''}`:i.status==='succeeded'?'完成':i.status==='failed'?'失败':i.status==='canceled'?'已取消':'等待'}
function render(){e.count.textContent=`${queue.length} / 10`;e.clear.hidden=!queue.length;e.list.innerHTML='';queue.forEach((i,n)=>{const row=document.createElement('div');row.className=`queue-item ${n===active?'is-active ':''}${i.status==='succeeded'?'is-done ':''}${i.status==='failed'?'is-error':''}`;row.innerHTML=`<img class="queue-thumb" src="${i.inputUrl}" alt=""><span class="queue-name" title="${i.file.name}">${i.file.name}</span><span class="queue-state">${text(i)}</span><button class="queue-remove" type="button" aria-label="取消或移除 ${i.file.name}">×</button>`;row.onclick=ev=>{if(!ev.target.closest('.queue-remove'))select(n)};row.querySelector('.queue-remove').onclick=ev=>{ev.stopPropagation();remove(n)};e.list.appendChild(row)});if(e.resultSelect){const previous=String(active);e.resultSelect.innerHTML=queue.length?queue.map((i,n)=>`<option value="${n}">${n+1}. ${i.file.name}</option>`).join(''):'<option value="">等待图片</option>';e.resultSelect.value=queue.length?previous:'';e.resultSelect.disabled=!queue.length}}
function setComparePosition(value){comparePosition=Math.max(0,Math.min(100,value));if(e.comparisonImage)e.comparisonImage.style.setProperty('--pos',`${comparePosition}%`)}
function select(n){if(!queue[n])return;active=n;const i=queue[n];if(e.resultSelect)e.resultSelect.value=String(n);e.status.textContent=text(i);e.input.src=i.inputUrl;if(i.outputUrl){e.output.src=i.outputUrl;e.comparison.hidden=false;e.footer.hidden=false;e.name.textContent=i.outputName;e.download.href=i.outputUrl;e.download.download=i.outputName;e.info.textContent=`${bytes(i.outputSize)} · ${i.outputType||'image'}`;setComparePosition(50)}else{e.comparison.hidden=true;e.footer.hidden=true}e.batchDownload.hidden=queue.filter(x=>x.status==='succeeded').length<2;render()}
async function remove(n){const i=queue[n];if(!i)return;if(i.eventSource)i.eventSource.close();if(i.jobId&&['queued','running'].includes(i.status))await fetch(`${base()}/api/jobs/${i.jobId}`,{method:'DELETE'}).catch(()=>{});URL.revokeObjectURL(i.inputUrl);queue.splice(n,1);active=Math.max(0,Math.min(active,queue.length-1));render();if(queue.length)select(active);else{e.status.textContent='等待图片';e.comparison.hidden=true;e.footer.hidden=true}}
function clearQueue(){if(submitting)return;queue.forEach(i=>{if(i.eventSource)i.eventSource.close();URL.revokeObjectURL(i.inputUrl)});queue=[];active=0;e.file.value='';render();e.comparison.hidden=true;e.footer.hidden=true;e.batchDownload.hidden=true;e.status.textContent='等待图片';e.progress.textContent='选择图片后开始'}
function path(id,p){return`./assets/model-comparison/${id}/${p}.webp`}function populate(){Object.entries(MODELS).forEach(([id,m])=>{const o=document.createElement('option');o.value=id;o.textContent=`${m.name} · ${id}`;e.model.appendChild(o);const c=document.createElement('button');c.type='button';c.className='model-card';c.dataset.model=id;c.innerHTML=`<div class="model-card-copy"><strong>${m.name}</strong><span>${m.description}</span></div><div class="model-card-images"><img src="${path(id,'before')}" alt="${m.name} 处理前示例"><img src="${path(id,'after')}" alt="${m.name} 处理后示例"><span>BEFORE</span><span>AFTER</span></div>`;c.onclick=()=>{if(submitting)return;e.model.value=id;update();closeDialog()};e.grid.appendChild(c)});update()}function update(){const id=e.model.value,m=MODELS[id];e.desc.textContent=m?.description||'—';e.triggerName.textContent=m?`${m.name} · ${id}`:'—';e.grid.querySelectorAll('.model-card').forEach(c=>c.classList.toggle('is-selected',c.dataset.model===id))}function openDialog(){if(submitting)return;e.dialog.hidden=false;document.body.classList.add('dialog-open')}function closeDialog(){e.dialog.hidden=true;document.body.classList.remove('dialog-open')}
function config(){const p=new URLSearchParams({model:e.model.value,scale:e.scale.value,format:e.format.value,tileSize:e.tile.value});return p}
function apply(i,j){i.status=j.status;i.position=j.position;i.progress=j.progress;i.stage=j.stage;i.error=j.error;if(j.output){i.outputUrl=base()+j.output.url;i.outputName=j.output.filename;i.outputSize=j.output.size;i.outputType=j.output.mime}render();if(queue[active]===i)select(active);maybeFinish()}
function maybeFinish(){if(!submitting||!queue.length||queue.some(i=>!['succeeded','failed','canceled'].includes(i.status)))return;submitting=false;e.start.disabled=false;e.trigger.disabled=false;e.start.querySelector('span').textContent='升图';e.progress.textContent=`任务已完成 ${queue.filter(i=>i.status==='succeeded').length} / ${queue.length}`;e.batchDownload.hidden=queue.filter(i=>i.status==='succeeded').length<2}
async function downloadBatch(){const items=queue.filter(i=>i.status==='succeeded'&&i.outputUrl);if(items.length<2||e.batchDownload.dataset.busy==='true')return;if(!window.JSZip)return error('批量下载组件尚未加载，请稍后重试。');e.batchDownload.dataset.busy='true';e.batchDownload.disabled=true;e.batchDownload.classList.add('is-busy');e.batchDownload.querySelector('span').textContent='正在打包…';e.progress.textContent=`正在准备 ${items.length} 张图片…`;try{const zip=new JSZip();for(let n=0;n<items.length;n++){const i=items[n];const r=await fetch(i.outputUrl);if(!r.ok)throw Error(`${i.outputName} 下载失败`);zip.file(i.outputName,await r.blob());e.progress.textContent=`正在打包 ${n+1} / ${items.length}…`}const blob=await zip.generateAsync({type:'blob'},meta=>{e.progress.textContent=`正在生成 ZIP ${Math.round(meta.percent)}%…`});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`enhance-results-${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);e.batchDownload.querySelector('span').textContent='已开始下载';e.progress.textContent=`已打包 ${items.length} 张图片`}catch(x){error(`批量下载失败：${x.message}`);e.batchDownload.querySelector('span').textContent='重试批量下载'}finally{setTimeout(()=>{e.batchDownload.dataset.busy='false';e.batchDownload.disabled=false;e.batchDownload.classList.remove('is-busy');if(e.batchDownload.querySelector('span').textContent==='已开始下载'||e.batchDownload.querySelector('span').textContent==='重试批量下载')e.batchDownload.querySelector('span').textContent='批量下载 ZIP'},1600)}}
function watch(i){if(!i.jobId)return;let es;const poll=()=>fetch(`${base()}/api/jobs/${i.jobId}`).then(r=>r.json()).then(d=>{apply(i,d.job);if(!['succeeded','failed','canceled'].includes(d.job.status))setTimeout(poll,2000)}).catch(()=>setTimeout(poll,4000));try{es=new EventSource(`${base()}/api/jobs/${i.jobId}/events`);i.eventSource=es;const onJob=ev=>{try{const j=JSON.parse(ev.data).job;apply(i,j);if(['succeeded','failed','canceled'].includes(j.status))es.close()}catch(_){}};es.addEventListener('job',onJob);es.onerror=()=>{es.close();poll()}}catch(_){poll()}poll()}
async function start(){clearError();if(!queue.length)return error('请先选择图片。');if(submitting)return;submitting=true;e.start.disabled=true;e.trigger.disabled=true;e.start.querySelector('span').textContent='任务进行中…';const p=config(),items=queue.filter(i=>i.status!=='succeeded'),total=items.length,batchId=(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`);items.forEach((i,n)=>{i.status='uploading';i.batchIndex=n});render();e.progress.textContent=`提交任务 0 / ${total}`;await Promise.all(items.map(async(i,n)=>{try{const r=await fetch(`${base()}/api/jobs?${p}`,{method:'POST',headers:{'Content-Type':i.file.type,'X-File-Name':encodeURIComponent(i.file.name),'X-Queue-Batch-Id':batchId,'X-Queue-Batch-Size':String(total),'X-Queue-Batch-Index':String(n)},body:i.file});const d=await r.json();if(!r.ok)throw Error(d.error?.message||`HTTP ${r.status}`);i.jobId=d.job.id;apply(i,d.job);watch(i)}catch(x){i.status='failed';error(`${i.file.name}：${x.message}`)}finally{e.progress.textContent=`已提交 ${Math.min(total,n+1)} / ${total}`;render()}}));maybeFinish()}
function updateCompareFromEvent(ev){if(!e.comparisonImage)return;const rect=e.comparisonImage.getBoundingClientRect();const point=ev.touches?ev.touches[0]:ev;setComparePosition(((point.clientX-rect.left)/rect.width)*100)}
e.file.onchange=x=>addFiles(x.target.files);e.clear.onclick=clearQueue;e.model.onchange=update;e.trigger.onclick=openDialog;e.batchDownload.onclick=downloadBatch;e.resultSelect.onchange=x=>select(Number(x.target.value));document.querySelectorAll('[data-close-model-dialog]').forEach(b=>b.onclick=closeDialog);document.onkeydown=x=>{if(x.key==='Escape'&&!e.dialog.hidden)closeDialog()};e.start.onclick=start;e.drop.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();e.file.click()}};['dragenter','dragover'].forEach(n=>e.drop.addEventListener(n,x=>{x.preventDefault();e.drop.classList.add('is-dragging')}));['dragleave','drop'].forEach(n=>e.drop.addEventListener(n,x=>{x.preventDefault();e.drop.classList.remove('is-dragging')}));e.drop.ondrop=x=>addFiles(x.dataTransfer.files);e.comparisonImage?.addEventListener('dragstart',ev=>{ev.preventDefault()});e.comparisonImage?.addEventListener('pointerdown',ev=>{draggingCompare=true;e.comparisonImage.setPointerCapture?.(ev.pointerId);updateCompareFromEvent(ev)});e.comparisonImage?.addEventListener('pointermove',ev=>{if(draggingCompare)updateCompareFromEvent(ev)});e.comparisonImage?.addEventListener('pointerup',()=>{draggingCompare=false});e.comparisonImage?.addEventListener('pointercancel',()=>{draggingCompare=false});setComparePosition(comparePosition);populate();
