const MODELS={"upscayl-standard-4x":{name:"Upscayl 标准",description:"适用于大多数图像，整体效果均衡。"},"upscayl-lite-4x":{name:"Upscayl 轻量版",description:"速度较快，质量损失较小。"},"high-fidelity-4x":{name:"高保真",description:"注重还原真实细节，适合照片。"},"remacri-4x":{name:"Remacri",description:"适合自然图像，强调锐度和细节。"},"ultramix-balanced-4x":{name:"Ultramix",description:"在锐度和细节之间取得平衡。"},"ultrasharp-4x":{name:"Ultrasharp",description:"重点增强边缘和纹理锐度。"},"digital-art-4x":{name:"数字艺术",description:"适合数字艺术、插画和动漫。"}};
const $=id=>document.getElementById(id),e={api:$('apiBaseInput'),pill:$('connectionPill'),conn:$('connectionText'),file:$('fileInput'),drop:$('dropzone'),list:$('fileQueue'),count:$('queueCount'),clear:$('clearFile'),model:$('modelSelect'),trigger:$('modelTrigger'),triggerName:$('modelTriggerName'),desc:$('modelDescription'),dialog:$('modelDialog'),grid:$('modelGrid'),scale:$('scaleSelect'),format:$('formatSelect'),tile:$('tileSelect'),gpu:$('gpuInput'),tta:$('ttaToggle'),start:$('upscaleButton'),health:$('healthButton'),error:$('errorMessage'),status:$('resultStatus'),loading:$('loadingResult'),title:$('loadingTitle'),copy:$('loadingCopy'),comparison:$('comparison'),input:$('inputPreview'),output:$('outputPreview'),footer:$('resultFooter'),info:$('outputInfo'),name:$('outputName'),download:$('downloadButton'),progress:$('progressText'),settingsTab:$('settingsTab'),settings:$('settingsPanel'),upscaleSettings:$('upscaleSettings')};
let queue=[],active=0,submitting=false;
const base=()=>e.api.value.trim().replace(/\/$/,''),bytes=b=>b<1048576?`${Math.max(1,Math.round(b/1024))} KB`:`${(b/1048576).toFixed(1)} MB`;
function conn(state,text){e.pill.dataset.state=state;e.conn.textContent=text}function error(text){e.error.textContent=text;e.error.hidden=false}function clearError(){e.error.hidden=true;e.error.textContent=''}
function valid(f){if(!/^image\/(png|jpeg|webp)$/.test(f.type))return'只支持 PNG、JPG/JPEG 和 WEBP 图片。';if(f.size>50*1048576)return'图片超过 API 的 50 MB 大小限制。';return''}
function addFiles(files){if(submitting)return;clearError();for(const f of Array.from(files||[])){const err=valid(f);if(err){error(`${f.name}：${err}`);continue}if(queue.length>=10||queue.some(x=>x.file.name===f.name&&x.file.size===f.size))continue;queue.push({file:f,status:'queued',inputUrl:URL.createObjectURL(f),jobId:null})}render();if(queue.length)select(queue.length-1)}
function text(i){return i.status==='queued'?`排队中${i.position?` · 前方 ${i.position-1}`:''}`:i.status==='running'?`处理中${i.progress!=null?` · ${i.progress}%`:''}`:i.status==='succeeded'?'完成':i.status==='failed'?'失败':i.status==='canceled'?'已取消':'等待'}
function render(){e.count.textContent=`${queue.length} / 10`;e.clear.hidden=!queue.length;e.list.innerHTML='';queue.forEach((i,n)=>{const row=document.createElement('div');row.className=`queue-item ${n===active?'is-active ':''}${i.status==='succeeded'?'is-done ':''}${i.status==='failed'?'is-error':''}`;row.innerHTML=`<img class="queue-thumb" src="${i.inputUrl}" alt=""><span class="queue-name" title="${i.file.name}">${i.file.name}</span><span class="queue-state">${text(i)}</span><button class="queue-remove" type="button" aria-label="取消或移除 ${i.file.name}">×</button>`;row.onclick=ev=>{if(!ev.target.closest('.queue-remove'))select(n)};row.querySelector('.queue-remove').onclick=ev=>{ev.stopPropagation();remove(n)};e.list.appendChild(row)})}
function select(n){if(!queue[n])return;active=n;const i=queue[n];e.status.textContent=text(i);e.input.src=i.inputUrl;if(i.outputUrl){e.output.src=i.outputUrl;e.comparison.hidden=false;e.footer.hidden=false;e.name.textContent=i.outputName;e.download.href=i.outputUrl;e.download.download=i.outputName;e.info.textContent=`${bytes(i.outputSize)} · ${i.outputType||'image'}`}else{e.comparison.hidden=true;e.footer.hidden=true}render()}
async function remove(n){const i=queue[n];if(!i)return;if(i.eventSource)i.eventSource.close();if(i.jobId&&['queued','running'].includes(i.status))await fetch(`${base()}/api/jobs/${i.jobId}`,{method:'DELETE'}).catch(()=>{});URL.revokeObjectURL(i.inputUrl);queue.splice(n,1);active=Math.max(0,Math.min(active,queue.length-1));render();if(queue.length)select(active);else{e.status.textContent='等待图片';e.comparison.hidden=true;e.footer.hidden=true}}
function clearQueue(){if(submitting)return;queue.forEach(i=>{if(i.eventSource)i.eventSource.close();URL.revokeObjectURL(i.inputUrl)});queue=[];active=0;e.file.value='';render();e.comparison.hidden=true;e.footer.hidden=true;e.status.textContent='等待图片';e.progress.textContent='选择图片后开始'}
function path(id,p){return`./assets/model-comparison/${id}/${p}.webp`}function populate(){Object.entries(MODELS).forEach(([id,m])=>{const o=document.createElement('option');o.value=id;o.textContent=`${m.name} · ${id}`;e.model.appendChild(o);const c=document.createElement('button');c.type='button';c.className='model-card';c.dataset.model=id;c.innerHTML=`<div class="model-card-copy"><strong>${m.name}</strong><span>${m.description}</span></div><div class="model-card-images"><img src="${path(id,'before')}" alt="${m.name} 处理前示例"><img src="${path(id,'after')}" alt="${m.name} 处理后示例"><span>BEFORE</span><span>AFTER</span></div>`;c.onclick=()=>{if(submitting)return;e.model.value=id;update();closeDialog()};e.grid.appendChild(c)});update()}function update(){const id=e.model.value,m=MODELS[id];e.desc.textContent=m?.description||'—';e.triggerName.textContent=m?`${m.name} · ${id}`:'—';e.grid.querySelectorAll('.model-card').forEach(c=>c.classList.toggle('is-selected',c.dataset.model===id))}function openDialog(){if(submitting)return;e.dialog.hidden=false;document.body.classList.add('dialog-open')}function closeDialog(){e.dialog.hidden=true;document.body.classList.remove('dialog-open')}
async function health(){clearError();conn('idle','检查中…');try{const r=await fetch(`${base()}/health`),d=await r.json();if(!r.ok)throw Error(`HTTP ${r.status}`);conn('ok',d.queueDepth?`API 在线 · 排队 ${d.queueDepth}`:'API 在线')}catch(x){conn('error','无法连接');error(`无法连接到 API：${x.message}。`)}}
function config(){const p=new URLSearchParams({model:e.model.value,scale:e.scale.value,format:e.format.value,tileSize:e.tile.value});if(e.gpu.value.trim())p.set('gpuId',e.gpu.value.trim());if(e.tta.checked)p.set('tta','true');return p}
function apply(i,j){i.status=j.status;i.position=j.position;i.progress=j.progress;i.stage=j.stage;i.error=j.error;if(j.output){i.outputUrl=base()+j.output.url;i.outputName=j.output.filename;i.outputSize=j.output.size;i.outputType=j.output.mime}render();if(queue[active]===i)select(active);maybeFinish()}
function maybeFinish(){if(!submitting||!queue.length||queue.some(i=>!['succeeded','failed','canceled'].includes(i.status)))return;submitting=false;e.start.disabled=false;e.trigger.disabled=false;e.start.querySelector('span').textContent='开始升图';e.progress.textContent=`任务已完成 ${queue.filter(i=>i.status==='succeeded').length} / ${queue.length}`;conn('ok','API 在线')}
function watch(i){if(!i.jobId)return;let es;const poll=()=>fetch(`${base()}/api/jobs/${i.jobId}`).then(r=>r.json()).then(d=>{apply(i,d.job);if(!['succeeded','failed','canceled'].includes(d.job.status))setTimeout(poll,2000)}).catch(()=>setTimeout(poll,4000));try{es=new EventSource(`${base()}/api/jobs/${i.jobId}/events`);i.eventSource=es;const onJob=ev=>{try{const j=JSON.parse(ev.data).job;apply(i,j);if(['succeeded','failed','canceled'].includes(j.status))es.close()}catch(_){}};es.addEventListener('job',onJob);es.onerror=()=>{es.close();poll()}}catch(_){poll()}poll()}
async function start(){clearError();if(!queue.length)return error('请先选择图片。');if(submitting)return;submitting=true;e.start.disabled=true;e.trigger.disabled=true;e.start.querySelector('span').textContent='任务进行中…';const p=config(),total=queue.length;for(let n=0;n<total;n++){const i=queue[n];if(i.status==='succeeded')continue;active=n;i.status='uploading';render();e.progress.textContent=`提交任务 ${n+1} / ${total}`;try{const r=await fetch(`${base()}/api/jobs?${p}`,{method:'POST',headers:{'Content-Type':i.file.type,'X-File-Name':encodeURIComponent(i.file.name)},body:i.file});const d=await r.json();if(!r.ok)throw Error(d.error?.message||`HTTP ${r.status}`);i.jobId=d.job.id;apply(i,d.job);watch(i)}catch(x){i.status='failed';render();error(`${i.file.name}：${x.message}`)}}maybeFinish()}
e.file.onchange=x=>addFiles(x.target.files);e.clear.onclick=clearQueue;e.model.onchange=update;e.trigger.onclick=openDialog;document.querySelectorAll('[data-close-model-dialog]').forEach(b=>b.onclick=closeDialog);document.onkeydown=x=>{if(x.key==='Escape'&&!e.dialog.hidden)closeDialog()};e.health.onclick=health;e.start.onclick=start;e.drop.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();e.file.click()}};['dragenter','dragover'].forEach(n=>e.drop.addEventListener(n,x=>{x.preventDefault();e.drop.classList.add('is-dragging')}));['dragleave','drop'].forEach(n=>e.drop.addEventListener(n,x=>{x.preventDefault();e.drop.classList.remove('is-dragging')}));e.drop.ondrop=x=>addFiles(x.dataTransfer.files);e.api.onchange=()=>conn('idle','未连接');e.settingsTab.onclick=()=>{const h=e.settings.hidden;e.settings.hidden=!h;e.upscaleSettings.hidden=h;document.querySelector('.tab.is-active')?.classList.remove('is-active');e.settingsTab.classList.toggle('is-active',h)};document.querySelector('.tab:not(#settingsTab)').onclick=()=>{e.settings.hidden=true;e.upscaleSettings.hidden=false;e.settingsTab.classList.remove('is-active');document.querySelector('.tab:not(#settingsTab)').classList.add('is-active')};populate();health();
